database:
  user: root
  password: delaro
  host: 25.51.52.101
  port: 3306
server:
  name: 'Metin2 newworld'
  url: 'https://www.mt2newworld2k22.com'
  domain: 'mt2newworld2k22.com'
  timezone: 'America/Bogota'
paymentwall:
  public_key: ''
  private_key: ''
captcha:
  enable: False
  public_key: ''
  private_key: ''
mail:
  host: 0.0.0.0
  port: 25
  password: 'breishell26'
  user: 'junior071325@gmail.com'
register:
  mail_activate_account: True
